service: go-lambda-test

provider:
  name: aws
  runtime: go1.x

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource:
        - "Fn::GetAtt": TestTable.Arn

resources:
  Resources:
    TestTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: golang-test
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  handler:
    handler: bin/handler
    events:
      - http:
          path: /user
          method: get
      - http:
          path: /user/{id}
          method: get
      - http:
          path: /user
          method: post
    environment:
      GIN_MODE: release
